version: '3.8'
services:
  # Dynamo DB local
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  # Redis local
  redis-master-local:
    image: redis:latest
    container_name: redis-master
    volumes:
      - "./docker/redis:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_REPLICATION_MASTER_PORT=6379
  redis-slave-local:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: >
      redis-server
      --slaveof redis-master 6379
      --appendonly yes

    # ms-core Java application
#  ms-core:
#    build:
#      context: .
#      dockerfile: "./ms-core/Dockerfile"
#    container_name: ms-core
#    depends_on:
#      - dynamodb-local
#      - redis-master-local
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=redis-master:6379
#      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000