version: '3.8'
services:
  # Dynamo DB local
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  # Redis local
  redis-master-local:
    image: redis:latest
    container_name: redis-master
    volumes:
      - "./docker/redis:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_REPLICATION_MASTER_PORT=6379
  redis-slave-local:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: >
      redis-server
      --slaveof redis-master 6379
      --appendonly yes

  ### Zipkin
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.24.2
    ports:
      - "9411:9411"

  ### Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  ### Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - prometheus
    volumes:
      - ./files/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    depends_on:
      - prometheus
  # ms-shorten Java application
#  ms-shorten:
#    build:
#      context: ./ms-shorten
#      dockerfile: Dockerfile
#    container_name: ms-shorten
#    depends_on:
#      - dynamodb-local
#      - redis-master-local
#    ports:
#      - "8082:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=redis-master:6379
#      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000