server:
  port: 0
  error:
    include-stacktrace: never
spring:
  application:
    name: ms-delete
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
config:
  application:
    x-api-key: test-ms-delete
  aws:
    access-key: test
    secret-key: test
    region: us-east-1
  dynamodb:
    endpoint: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/delete
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  level:
    root: DEBUG