server:
  port: 0
  error:
    include-stacktrace: never
spring:
  application:
    name: ms-redirect
  redis:
    host: localhost
    port: 6379
    password: redis
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    request:
      compression-type: snappy
      buffer-memory: 33554432
    consumer:
      group-id: redirect-listener
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
config:
  application:
    x-api-key: test-ms-redirect
    cache:
      # time in minutes
      get-url-expire-time: 720
  aws:
    access-key: test
    secret-key: test
    region: us-east-1
  dynamodb:
    endpoint: http://localhost:8000
  kafka-topics:
    redirect:
      request: redirect-request-topic
      response: redirect-response-topic
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/redirect
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  level:
    root: INFO