server:
  port: 8080
spring:
  application:
    name: ms-core
  redis:
    host: localhost
    port: 6379
    password: redis
config:
  application:
    cache:
      load-urls-in-cache: true
      # time in minutes
      urls-expire-time: 720
      save-urls-limit: 20000
    x-api-key:
        ms-shorten: test-ms-shorten
        ms-redirect: test-ms-redirect
        ms-delete: test-ms-delete
        ms-info: test-ms-info
        ms-auth: test-ms-auth
        ms-user: test-ms-user
  aws:
    access-key: test
    secret-key: test
    region: us-east-1
  dynamodb:
    configure: true
    endpoint: http://localhost:8000
    region: us-west-1
    access-key: test
    secret-key: test
    tables:
      urls:
        name: urls
        read: 10
        write: 10
        indexes:
          createdAt:
            read: 5
            write: 5
          userid:
            read: 10
            write: 10
      users:
        name: users
        read: 5
        write: 5
      stats:
        name: stats
        read: 5
        write: 5
