server:
  port: 0
spring:
  application:
    name: ms-core
  redis:
    host: localhost
    port: 6379
    password: redis
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
config:
  application:
    cache:
      load-urls-in-cache: true
      # time in minutes
      urls-expire-time: 720
      save-urls-limit: 20000
    x-api-key:
        ms-shorten: test-ms-shorten
        ms-redirect: test-ms-redirect
        ms-delete: test-ms-delete
        ms-info: test-ms-info
        ms-auth: test-ms-auth
        ms-user: test-ms-user
  aws:
    access-key: test
    secret-key: test
    region: us-east-1
  dynamodb:
    configure: true
    endpoint: http://localhost:8000
    region: us-west-1
    access-key: test
    secret-key: test
    tables:
      urls:
        name: urls
        read: 10
        write: 10
        indexes:
          createdAt:
            read: 5
            write: 5
          userid:
            read: 10
            write: 10
      users:
        name: users
        read: 5
        write: 5
      stats:
        name: stats
        read: 5
        write: 5
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/api/v1/core
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  level:
    root: DEBUG